
#' \code{get.SCOPE.outputs} get the outputs from SCOPE model
#'
#' @param data.sim a list elements generated by the SCOPE model
#' @param N.sims a vector with number of simulations generated by the SCOPE model
#' @param LUT a LUT with the inputss used in the SCOPE model
#' @param path.out  path for saving the main files
#' @param get.plots  is true, intermediate plots will be generated in Plot folder
#' @param get.more.inputs  is true, intermediate plots will be generated in Additional.inputs folder
#' @author Carlos Camino (Ported version into R)
#'
#' @example
#'

get.SCOPE.outputs <-function(data.sim, N.sims,LUT,path.out,get.plots,
                             get.more.inputs) {



  if (missing(data.sim)){
   stop('an SCOPE object with simulations is needed ...')
  }

  if (missing(LUT)){
    stop('The used LUT for generating the simulations is needed ...')
  }


  if (missing(get.plots)){
    get.plots = F
  }



  if (missing(N.sims)){
    N.sims = 1
  }




  if (N.sims == 1 ){


    if ( length(get.more.inputs) >= 1){

     if (is.null(names(db.sim)) == T){
      ##  This for deafult options
       ### save outputs with a single simulation
       get.outs.in(data.sim=data.sim[[1]],LUT=LUT,path.out=path.out,
                   get.plots=get.plots,get.more.inputs=get.more.inputs)

     } else {
       ### save outputs with a single simulation
       get.outs.in(data.sim=data.sim,LUT=LUT,path.out=path.out,
                   get.plots=get.plots,get.more.inputs=get.more.inputs)
     }


    } else {
      ### save outputs with a single simulation
      get.outs.in(data.sim=data.sim,LUT=LUT,path.out=path.out,
                  get.plots=get.plots)
    }


  } else {

    if (missing(get.more.inputs)){
      ### save outputs of a LUT with n simulations
      get.outs.lut(data.sim=data.sim,LUT=LUT,path.out=path.out,get.plots=get.plots, nSamples=length(data.sim))

    } else {
      message('get.more.inputs is not implemented when N.sims is > 1, next time')
      ### save outputs of a LUT with n simulations
      get.outs.lut(data.sim=data.sim,LUT=LUT,path.out=path.out,get.plots=get.plots, nSamples=length(data.sim))


    }


  }

}
