
#' \code{get.outs.in} get the outputs from the SCOPE model. This code is for single simulations
#'
#' @param data.sim a list elements generated by the SCOPE model
#' @param LUT a list of inputs used by the SCOPE model
#' @param path.out  path for saving the main files
#' @param get.plots  is true, intermediate plots will be generated in Plot folder
#' @param get.more.inputs  is true, intermediate plots will be generated in Additional.inputs folder
#' @author Carlos Camino (Ported version into R)
#'
#' @example
#' get.outs(data.sim)

get.outs.in <-function(data.sim, LUT,path.out,get.plots,
                       get.more.inputs){

  #if (!require("data.table")) { install.packages("data.table"); require("data.table") }  ### hsdar for PROSAIL
  # data.sim = db.sim
  # Get the current system time
  current_time <- format(Sys.time(), "%Y-%m-%d_%H-%M-%S")

  if (missing(get.plots)){
    get.plots = FALSE
  }


  if (missing(path.out)) {
    path_outs <- 'outs/'
    message('outs/ folder will be used for the SCOPE outputs')


    if (!dir.exists(path_outs)) {
      dir.create(path_outs)
    }

    # Create a folder with the current system time as part of the folder name
    folder_out <- paste(path_outs, current_time, sep = "")
    dir.create(folder_out)


    if (get.plots == T) {
      folder_for_plots <- paste(path_outs, current_time,'/Plots/',sep = "")
      dir.create(folder_for_plots)

    }

    if (length(get.more.inputs) >= 1) {
      folder.more.inputs <- paste(path_outs, current_time,'/Additional.inputs/', sep = "")
      dir.create(folder.more.inputs)
    }

  } else {

    path_outs <- path.out
    if (!dir.exists(path_outs)) {
      dir.create(path_outs)
    }
    # Create a folder with the current system time as part of the folder name
    folder_out <- paste(path_outs, current_time, sep = "")
    dir.create(folder_out)

    if (get.plots == T) {
      folder_for_plots <- paste(path_outs, current_time,'/Plots/', sep = "")
      dir.create(folder_for_plots)

    }

    if (length(get.more.inputs) >= 1) {
      folder.more.inputs <- paste(path_outs, current_time,'/Additional.inputs/', sep = "")
      dir.create(folder.more.inputs)

    }

  }

  # Create a folder with the current system time as part of the folder name
  folder_out_parameters <- paste(path_outs, current_time,'/Parameters/', sep = "")
  dir.create(folder_out_parameters)

  message <- "the SCOPE model uses the version 2.1 integrated in the SCOPEinR package "
  file_readme <-paste(folder_out_parameters,"/SCOPEversion.txt",sep='')
  writeLines(message, file_readme)
  # save using data.table
  data.table::fwrite(LUT, paste(folder_out_parameters,"/inputLUT.csv",sep=''))


  ### get main inputs from list
  data.spectral <- data.sim$data.spectral
  data.rad <- data.sim$data.rad
  data.canopy <- data.sim$data.canopy
  data.meteo <- data.sim$data.meteo
  data.resistance <- data.sim$resist_out
  data.fluxes <- data.sim$data.fluxes
  data.leafopt <- data.sim$data.leafopt



  ##############################################################################################################################
  # 1.1 Get Reflectance ----
  ##############################################################################################################################

  df.rfl <- data.frame(wave=data.spectral$wlS, reflapp =  data.rad$reflapp, refl =  data.rad$refl,
                       rsd=data.rad$rsd, rso=data.rad$rso,
                       rdd=data.rad$rdd, rdo=data.rad$rdo)

  df.rsd <- data.frame(wave=data.spectral$wlS, rsd=data.rad$rsd)
  df.rso <- data.frame(wave=data.spectral$wlS, rso=data.rad$rso)
  df.rdd <- data.frame(wave=data.spectral$wlS, rdd=data.rad$rdd)
  df.rdo <- data.frame(wave=data.spectral$wlS, rdo=data.rad$rdo)
  df.reflapp <- data.frame(wave=data.spectral$wlS, reflapp=data.rad$reflapp)
  df.refl <- data.frame(wave=data.spectral$wlS, reflapp=data.rad$refl)

  # save using data.table
  data.table::fwrite(df.rsd, paste(folder_out,"/rsd.csv",sep=''))
  data.table::fwrite(df.rso, paste(folder_out,"/rso.csv",sep=''))
  data.table::fwrite(df.rdd, paste(folder_out,"/rdd.csv",sep=''))
  data.table::fwrite(df.rdo, paste(folder_out,"/rdo.csv",sep=''))
  data.table::fwrite(df.reflapp, paste(folder_out,"/reflapp.csv",sep=''))
  data.table::fwrite(df.refl, paste(folder_out,"/refl.csv",sep=''))



  if (get.plots == T) {

    p.rfl <- ggplot(data = df.rfl, aes(x = wave, y = reflapp)) +

      geom_line(aes(y = rsd, color = 'rsd'), linewidth = 0.5) +
      geom_line(aes(y = rso, color = 'rso'), linewidth = 0.5) +
      geom_line(aes(y = rdd, color = 'rdd'), linewidth = 0.5) +
      geom_line(aes(y = rdo, color = 'rdo'), linewidth = 0.5) +
      geom_line(aes(y = reflapp, color = 'reflapp'), linewidth = 0.5) +
      geom_line(aes(y = refl, color = 'refl'), linewidth = 0.5) +
      scale_color_manual(name = 'reflectance',
                         values = c('reflapp' = 'forestgreen',
                                    'refl' = 'darkolivegreen1',
                                    'rsd' ='darkcyan',
                                    'rso' ='dodgerblue3',
                                    'rdd' ='darkgoldenrod3',
                                    'rdo' ='brown2')) +
      theme_bw() + xlim(400,2499)  + ylab("reflectance") +
      theme(legend.position = "top") +
      guides(color = guide_legend(title = NULL))

    #print(p.rfl)

    ggsave(paste(folder_for_plots,'1-reflectance.png',sep=''),plot=p.rfl,
           width = 10, height = 10,  dpi = 300,units = "cm")



  }


  ##############################################################################################################################
  # 1.2 Get Irradiance ----
  ##############################################################################################################################

  df.irrad <- data.frame(wave=data.spectral$wlS, Esun_ = data.rad$Esun_,
                         Esky_=data.rad$Esky_)

  df.Esun_ <- data.frame(wave=data.spectral$wlS, Esun_=data.rad$Esun_)
  # save using data.table
  data.table::fwrite(df.Esun_, paste(folder_out,"/Esun.csv",sep=''))

  df.Esky_ <- data.frame(wave=data.spectral$wlS, Esky_=data.rad$Esky_)
  # save using data.table
  data.table::fwrite(df.Esky_, paste(folder_out,"/Esky.csv",sep=''))

  if (get.plots == T) {

    p.irrad<- ggplot(data = df.irrad, aes(x = wave)) +
      geom_line(aes(y = Esun_, color = 'Esun_'), linewidth = 0.5) +
      geom_line(aes(y = Esky_, color = 'Esky_'), linewidth = 0.5) +

      scale_color_manual(name = 'Irradiance',
                         values = c('Esun_' = 'orange',
                                    'Esky_' ='grey')) +

      theme_bw() + xlim(400,2499) +
      theme(legend.position = "top") +ylab("Irradiance") +
      guides(color = guide_legend(title = NULL))
    #print(p.irrad)
    ggsave(paste(folder_for_plots,'2-Irradiance.png',sep=''),plot=p.irrad,
           width = 10, height = 10,  dpi = 300,units = "cm")



  }

  ##############################################################################################################################
  # 1.3 Get Radiance spectrum  excluding/adding fluorescence  (W m-2 um-1 sr-1)   ----
  ##############################################################################################################################

  df.Lotot <- data.frame(wave=data.spectral$wlS, Lotot_ = data.rad$Lotot_,Lototf_ = data.rad$Lototf_)


  df.Lotot_ <- data.frame(wave=data.spectral$wlS, Lotot_ = data.rad$Lotot_)
  # save using data.table
  data.table::fwrite(df.Lotot_, paste(folder_out,"/Lo_spectrum.csv",sep=''))

  df.Lototf_ <- data.frame(wave=data.spectral$wlS,Lototf_ = data.rad$Lototf_)
  # save using data.table
  data.table::fwrite(df.Lototf_, paste(folder_out,"/Lo_spectrum_includingF.csv",sep=''))


  if (get.plots == T) {

    p.Lotot <- ggplot(data = df.Lotot, aes(x = wave)) +
      geom_line(aes(y = Lotot_, color = 'Lotot_'), linewidth = 0.5) +
      geom_line(aes(y = Lototf_, color = 'Lototf_'), linewidth = 0.5) +

      scale_color_manual(name = 'Radiance',
                         values = c('Lotot_' = 'orange','Lototf_' ='black')) +

      theme_bw() + xlim(400,900) +
      theme(legend.position = "top") +ylab("Radiance") +
      guides(color = guide_legend(title = NULL))

    #print(p.Lotot)
    ggsave(paste(folder_for_plots,'3-Radiance_excluding_addingFluorescence.png',sep=''),plot=p.Lotot,
           width = 10, height = 10,  dpi = 300,units = "cm")

    p.Lotot2 <- ggplot(data = df.Lotot, aes(x = wave)) +
      geom_line(aes(y = Lotot_, color = 'Lotot_'), linewidth = 0.5) +
      geom_line(aes(y = Lototf_, color = 'Lototf_'), linewidth = 0.5) +

      scale_color_manual(name = 'Radiance',
                         values = c('Lotot_' = 'orange','Lototf_' ='darkcyan')) +

      theme_bw() + xlim(640,900) +
      theme(legend.position = "top") +ylab("Radiance") +
      guides(color = guide_legend(title = NULL))

    #print(p.Lotot2)
    ggsave(paste(folder_for_plots,'3-Radiance_excluding_addingFluorescence_2.png',sep=''),plot=p.Lotot2,
           width = 10, height = 10,  dpi = 300,units = "cm")
  }



  ##############################################################################################################################
  # 1.4 Get Radiation  ----
  ##############################################################################################################################

  df.radiation <- data.frame(

    ShortIn = data.meteo[['Rin']], ## units inW m-2
    ShortLong = data.meteo[['Rli']], ## units inW m-2
    HemisOutIn = data.rad[['Eouto']], ## units in W m-2
    HemisOutLong = data.rad[['Eoutte']], ## units in W m-2

    Lo = data.rad[['Lo']], ## units in W m-2 sr -1
    Lot = data.rad[['Lot']], ## units in W m-2 sr -1
    Lote = data.rad[['Lote']]) ## units in W m-2 sr -1

  # save using data.table
  data.table::fwrite(df.radiation, paste(folder_out,"/radiation.csv",sep=''))


  df.radiation.units <- data.frame(ShortIn = 'W m-2', ShortLong = 'W m-2',
                                   HemisOutIn = 'W m-2', HemisOutLong = 'W m-2',
                                   Lo = 'W m-2 sr -1', Lot = 'W m-2 sr -1', Lote = 'W m-2 sr -1')


  # save using data.table
  data.table::fwrite(df.radiation.units, paste(folder_out,"/radiation_units.csv",sep=''))


  ##############################################################################################################################
  # 1.5 Get ApAR values  ----
  ##############################################################################################################################

  df.apar <-data.frame(
    # EPAR and PAR
    iPAR = data.rad[['PAR']], ## units in umol m-2 s-1
    iPARE = data.rad[['EPAR']], ## units in W m-2
    ## LAI sunit/sgaded
    LAIsunlit = data.canopy[['LAIsunlit']], ## m2 m-2
    LAIshaded = data.canopy[['LAIshaded']], ## m2 m-2
    # Total aPAR
    aPARTot = data.canopy[['Pntot']], ## units in umol m-2 s-1
    aPARTotSun = data.canopy[['Pnsun']], ## units in umol m-2 s-1
    aPARTotShaded = data.canopy[['Pnsha']], ## units in umol m-2 s-1

    ## Total aPAR Cab
    aPARCabTot = data.canopy[['Pntot_Cab']], ## units in umol m-2 s-1
    aPARCabSun = data.canopy[['Pnsun_Cab']], ## units in umol m-2 s-1
    aPARCabShaded = data.canopy[['Pnsha_Cab']], ## units in umol m-2 s-1
    ## Total aPAR Car
    aPARCarTot =data.canopy[['Pntot_Car']], ## units in umol m-2 s-1
    aPARCarSun =data.canopy[['Pnsun_Car']], ## units in umol m-2 s-1
    aPARCarShaded =data.canopy[['Pnsha_Car']], ## units in umol m-2 s-1

    # Total aPAR E
    aPARTotE = data.canopy[['Rntot_PAR']], ## units in W m-2
    aPARTotSunE = data.canopy[['Rnsun_PAR']], ##  units in W m-2
    aPARTotShadedE = data.canopy[['Rnsha_PAR']], ## units in m-2
    # Total aPAR E Cab
    aPARTotCabE = data.canopy[['Rntot_Cab']], ## units in W m-2
    aPARTotSunCabE = data.canopy[['Rnsun_Car']], ##  units in W m-2
    aPARTotShadedCabE = data.canopy[['Rnsha_Car']], ## units in W m-2

    # Total aPAR E Car
    aPARTotCarE = data.canopy[['Rntot_Car']], ## units in W m-2
    aPARTotSunCarE = data.canopy[['Rnsun_Car']], ##  units in W m-2
    aPARTotShadedCarE = data.canopy[['Rnsha_Car']]## units in W m-2
  )

  # save using data.table
  data.table::fwrite(df.apar, paste(folder_out,"/aPAR.csv",sep=''))


  ##############################################################################################################################
  # 1.6 Get resistance values  ----
  ##############################################################################################################################

  df.resistance <-data.frame(
    ra = data.resistance[['raws']], ## units in s m-1
    raforSoil = data.resistance[['rss']], ## units in s m-1
    rss = data.resistance[['rss']], ## units in s m-1
    ustar = data.resistance[['ustar']]) ## units in m2 s-1

  # save using data.table
  data.table::fwrite(df.resistance, paste(folder_out,"/resistance.csv",sep=''))

  df.resistance.units <-data.frame(ra = 's m-1', raforSoil = 's m-1',
                                   rss = 's m-1', ustar ='m2 s-1')

  # save using data.table
  data.table::fwrite(df.resistance.units, paste(folder_out,"/resistance_units.csv",sep=''))

  ##############################################################################################################################
  # 1.7 Get vegetation values  ----
  ##############################################################################################################################

  df.vegatation <-data.frame(
    Photosintesis = data.canopy[['A']], ## units in umol m-2 s-1
    Electron_transport = data.canopy[['Ja']], ## units in umol m-2 s-1
    NPQ_energy = data.canopy[['ENPQ']], ## units in W m-2
    NPQ_photon = data.canopy[['PNPQ']], ## units in umol photons-1
    LST = data.canopy[['LST']], ## units in K
    emis = data.canopy[['emis']]) ##  no units

  data.table::fwrite(df.vegatation, paste(folder_out,"/vegatation.csv",sep=''))

  df.vegatation.units <-data.frame(Photosintesis = 'umol m-2 s-1', Electron_transport = 'umol m-2 s-1',
                                   NPQ_energy = 'W m-2',  NPQ_photon = 'umol photons-1',
                                  LST = 'Kelvin', emis = '--')
  # save using data.table
  data.table::fwrite(df.vegatation.units, paste(folder_out,"/vegatation_units.csv",sep=''))

  ##############################################################################################################################
  # 1.8 Get Sigma Fluorescence values  ----
  ##############################################################################################################################


  df.sigmaF <- data.frame(wave=data.spectral$wlF, sigmaF = data.rad$sigmaF)
  # save using data.table
  data.table::fwrite(df.sigmaF, paste(folder_out,"/SigmaF.csv",sep=''))
  if (get.plots == T) {

    p.sigmaF <- ggplot(data = df.sigmaF, aes(x = wave)) +
      geom_line(aes(y = sigmaF, color = 'sigmaF'), linewidth = 0.5) +

      scale_color_manual(name = 'sigmaF',
                         values = c('sigmaF' = 'black')) +

      theme_bw() + xlim(640,850) +
      theme(legend.position = "top") +ylab("sigmaF") +
      guides(color = guide_legend(title = NULL))

    #print(p.sigmaF)

    ggsave(paste(folder_for_plots,'4-SigmaFluorescence.png',sep=''),plot=p.sigmaF,
           width = 10, height = 10,  dpi = 300,units = "cm")

  }

  ##############################################################################################################################
  # 1.8 Get Hemispherically Integrated upwelling radiance or TOC upward radiation  (W m-2 um-1)   ----
  ##############################################################################################################################

  df.Eout_ <- data.frame(wave=data.spectral$wlS, Eout_ = data.rad$Eout_)

  # save using data.table
  data.table::fwrite(df.Eout_, paste(folder_out,"/Eout_spectrum.csv",sep=''))
  if (get.plots == T) {

    p.Eout_ <- ggplot(data = df.Eout_, aes(x = wave)) +
      geom_line(aes(y = Eout_, color = 'Eout_'), linewidth = 0.5) +

      scale_color_manual(name = 'Radiance',
                         values = c('Eout_' = 'black')) +

      theme_bw() + xlim(400,2499) +
      theme(legend.position = "top") +ylab("Radiance") +
      guides(color = guide_legend(title = NULL))

   #print(p.Eout_)
    ggsave(paste(folder_for_plots,'5-Hemispherically_Integrated_upwelling_radiance.png',sep=''),plot=p.Eout_,
           width = 10, height = 10,  dpi = 300,units = "cm")
  }

  ##############################################################################################################################
  # 1.9 Get Fluxes  ----
  ##############################################################################################################################

  df.fluxes <- as.data.frame(t(unlist(data.fluxes)))
  # save using data.table
  data.table::fwrite(df.fluxes, paste(folder_out,"/fluxes.csv",sep=''))

  df.fluxes.units<-data.frame( Rnctot = 'W m-2', lEctot = 'W m-2', Hctot = 'W m-2', Actot = 'umol m-2 s-1',
    Tcave = 'C', Rnstot = 'W m-2',  lEstot = 'W m-2', Hstot= 'W m-2',
    Gtot= 'W m-2', Tsave = 'C',Rntot = 'W m-2', lEtot ='W m-2',
    Htot ='W m-2')
  # save using data.table
  data.table::fwrite(df.fluxes.units, paste(folder_out,"/fluxes_units.csv",sep=''))


  ##############################################################################################################################
  # 1.10 Get fluorescence  (W m-2 um-1 sr-1)   ----
  ##############################################################################################################################

  df.LoF <- data.frame(wave=data.spectral$wlF, LoF_ = data.rad$LoF_,
                       LoF_sunlit = data.rad$LoF_sunlit,
                       LoF_shaded= data.rad$LoF_shaded,
                       LoF_scattered= data.rad$LoF_scattered,
                       LoF_soil= data.rad$LoF_soil,
                       F.all.Leaves = data.rad$Femliave_,
                       EoutF_=data.rad$EoutF_,
                       EoutFrc_ = data.rad$EoutFrc_)

  # save using data.table
  df.LoF_ <- data.frame(wave=data.spectral$wlF, LoF_ = data.rad$LoF_)
  data.table::fwrite(df.LoF_, paste(folder_out,"/fluorescence.csv",sep=''))

  LoF_sunlit <- data.frame(wave=data.spectral$wlF, LoF_sunlit = data.rad$LoF_sunlit)
  data.table::fwrite(LoF_sunlit, paste(folder_out,"/fluorescence_sunlit.csv",sep=''))

  LoF_shaded <- data.frame(wave=data.spectral$wlF, LoF_shaded = data.rad$LoF_shaded)
  data.table::fwrite(LoF_shaded, paste(folder_out,"/fluorescence_shaded.csv",sep=''))

  LoF_scattered <- data.frame(wave=data.spectral$wlF, LoF_scattered = data.rad$LoF_scattered)
  data.table::fwrite(LoF_scattered, paste(folder_out,"/fluorescence_scattered.csv",sep=''))

  LoF_soil <- data.frame(wave=data.spectral$wlF, LoF_soil = data.rad$LoF_soil)
  data.table::fwrite(LoF_soil, paste(folder_out,"/fluorescence_soil.csv",sep=''))

  df.LoF_ <- data.frame(wave=data.spectral$wlF, LoF_ = data.rad$LoF_)
  data.table::fwrite(df.LoF_, paste(folder_out,"/fluorescence.csv",sep=''))

  # save using data.table
  df.Femliave_ <- data.frame(wave=data.spectral$wlF, Femliave_ = data.rad$Femliave_)
  data.table::fwrite(df.Femliave_, paste(folder_out,"/fluorescence_All_Leaves.csv",sep=''))

  # save using data.table
  df.EoutF_ <- data.frame(wave=data.spectral$wlF, EoutF_ = data.rad$EoutF_)
  data.table::fwrite(df.EoutF_, paste(folder_out,"/fluorescence_hemis.csv",sep=''))

  # save using data.table
  df.EoutFrc_ <- data.frame(wave=data.spectral$wlF, EoutFrc_ = data.rad$EoutFrc_)
  data.table::fwrite(df.EoutFrc_, paste(folder_out,"/fluorescence_ReabsCorr.csv",sep=''))


  if (get.plots == T) {

    p.LoF <- ggplot(data = df.LoF, aes(x = wave)) +
      geom_line(aes(y = LoF_, color = 'LoF_'), linewidth = 0.5) +
      geom_line(aes(y = F.all.Leaves, color = 'F.all.Leaves'), linewidth = 0.5) +
      geom_line(aes(y = EoutF_, color = 'EoutF_'), linewidth = 0.5) +
      geom_line(aes(y = EoutFrc_, color = 'EoutFrc_'), linewidth = 0.5) +
      scale_color_manual(name = 'Fluorescence',
                         values = c('LoF_' = 'darkgoldenrod3',
                                    'EoutF_' = 'brown2',
                                    'EoutFrc_' = 'navyblue',
                                    'F.all.Leaves' ='darkcyan'),) +

      theme_bw() + xlim(640,850) +
      theme(legend.position = "top") +ylab("Fluorescence") +
      guides(color = guide_legend(title = NULL))

    #print(p.LoF)

    ggsave(paste(folder_for_plots,'6-fluorescence.png',sep=''),plot=p.LoF,
           width = 10, height = 10,  dpi = 300,units = "cm")



    p.LoF <- ggplot(data = df.LoF, aes(x = wave)) +
      geom_line(aes(y = LoF_, color = 'LoF_'), linewidth = 0.5) +
      geom_line(aes(y = LoF_sunlit, color = 'LoF_sunlit'), linewidth = 0.5) +
      geom_line(aes(y = LoF_shaded, color = 'LoF_shaded'), linewidth = 0.5) +
      geom_line(aes(y = LoF_soil, color = 'LoF_soil'), linewidth = 0.5) +
      geom_line(aes(y = LoF_scattered, color = 'LoF_scattered'), linewidth = 0.5) +
      scale_color_manual(name = 'Fluorescence',
                         values = c('LoF_' = 'darkgoldenrod3',
                                    'LoF_sunlit' = 'orange',
                                    'LoF_shaded' = 'navyblue',
                                    'LoF_soil' = 'black',
                                    'Fluorescence' ='darkcyan'),) +

      theme_bw() + xlim(640,850) +
      theme(legend.position = "top") +ylab("Radiance") +
      guides(color = guide_legend(title = NULL))

    #print(p.LoF)

    ggsave(paste(folder_for_plots,'6-fluorescence_v2.png',sep=''),plot=p.LoF,
           width = 10, height = 10,  dpi = 300,units = "cm")
  }


  ##############################################################################################################################
  # 1.10 Get fluorescence scalar values     ----
  ##############################################################################################################################

  df.scalar <-data.frame(
    F_1stPeak = data.rad[['F685']],
    wl_1stPeak = data.rad[['wl685']],
    F_2ndPeak = data.rad[['F740']],
    wl_2ndPeak = data.rad[['wl740']],
    F684 = data.rad[['F684']],
    F761 = data.rad[['F761']],
    LFtot = data.rad[['LoutF']],
    EFtot = data.rad[['EoutF']],
    EFtot_RC = data.rad[['EoutFrc']])

  # save using data.table
  data.table::fwrite(df.scalar, paste(folder_out,"/fluorescence_scalar.csv",sep=''))

  df.scalar.units<-data.frame( F_1stPeak = 'W m-2 um-1 sr-1', wl_1stPeak = 'nm',
                               F_2ndPeak = 'W m-2 um-1 sr-1', wl_2ndPeak = 'nm',
                               F684 = 'W m-2 um-1 sr-1', F761 = 'W m-2 um-1 sr-1',
                               LFtot= 'W m-2 sr-1',EFtot = 'W m-2', EFtot_RC ='W m-2')
  # save using data.table
  data.table::fwrite(df.scalar, paste(folder_out,"/fluorescence_scalar_units.csv",sep=''))



  ##############################################################################################################################
  # 1.1 Get Additional SCOPE inputs by user ----
  ##############################################################################################################################
  #get.more.inputs<-c('refl','lidf','LIDFb','Ft_Fo','rdo')
  #data.sim = db.sim

  for (j in (1:length(get.more.inputs))) {

    j_input <-get.more.inputs[[j]]

    names.db <- unlist(names(data.sim))
    # Find elements in the list
    for (i in 1:length(names.db)){

      get.names <-names(data.sim[[names.db[i]]])
      position <- which(get.names %in% j_input)



      if (length(position) > 0) {
        #print(names.db[i])
        #print(names(data.sim[[names.db[i]]][position]))
        name_ <- names(data.sim[[names.db[i]]][position])
        var_ = data.sim[[names.db[i]]][[name_]]

        if (is.vector(var_)) {
          # Handle vectors and matrices

          if (length(var_) > 1){
            var.vector <- cbind(as.data.frame(var_))
            colnames(var.vector)<-name_
          } else {
            var.vector <- (as.data.frame(var_))
            colnames(var.vector)<-name_
          }

          write.csv(var.vector, paste(folder.more.inputs,'/Inputs-',names.db[i],'-',name_,'.csv',sep=''),row.names = F)


        } else if (is.matrix(var_)) {


          var.matrix <-var_
          dimension <-dim(var.matrix)[2]

          if (dimension[[1]] == length(data.sim$data.spectral$wlP)) {
            ## 1:2001 wave
            colnames(var_) = paste('wave.', data.sim$data.spectral$wlP)

          } else if ( dimension[[1]]== length(data.sim$data.spectral$wlS)) {
            ## 1:2162 wave
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlS)

          } else if (dimension[[1]] == length(data.sim$data.spectral$wlF)) {
            ## 1:211 wave
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlF)

          } else if (dimension[[1]] == length(data.sim$data.spectral$wlE)) {
            ## 1:351 wave
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlE)

          } else if (dimension[[1]] == length(data.sim$data.spectral$wlO)) {
            ## 1:2001 wave
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlO)

          }  else if (dimension[[1]] == length(data.sim$data.spectral$wlT)) {
            ## 1:161 wave
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlT)

          }  else if (dimension[[1]] == length(data.sim$data.spectral$wlZ)){
            ## 500 600 1
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlZ)

          } else if (dimension[[1]] == length(data.sim$data.spectral$wlPAR)) {
            ## 1:3001
            colnames(var_) = paste('wave.',data.sim$data.spectral$wlPAR)


          }

          write.csv(var.matrix, paste(folder.more.inputs,'/Inputs-',names.db[i],'-',name_,'.csv',sep=''),row.names = F)


        }


      }

    }



  }

  ##############################################################################################################################
  # End code for adding the additional SCOPE inputs selected by user ----
  ##############################################################################################################################

}


