
#' \code{get.outs.lut} get the outputs from SCOPE model. This code is for a LUT of simulations
#'
#' @param data.sim  list elements generated by the SCOPE model
#' @param LUT a list of inputs used in the SCOPE model
#' @param path.out  path for saving the main files
#' @param get.plots  is true, intermediate plots will be generated in Plot folder
#' @author Carlos Camino (Ported version into R)
#'
#' @example
#' get.outs.lut(data.sim)

get.outs.lut <-function(data.sim, LUT,path.out,get.plots, nSamples){

  #if (!require("data.table")) { install.packages("data.table"); require("data.table") }  ### hsdar for PROSAIL

  # Get the current system time
  current_time <- format(Sys.time(), "%Y-%m-%d_%H-%M-%S")

  if (missing(get.plots)){
    get.plots = FALSE
  }


  if (missing(path.out)) {
    path_outs <- 'outs/'
    message('outs/ folder will be used for the SCOPE outputs')


    if (!dir.exists(path_outs)) {
      dir.create(path_outs)
    }

    # Create a folder with the current system time as part of the folder name
    folder_out <- paste(path_outs, current_time, sep = "")
    dir.create(folder_out)

    if (get.plots == T) {
      folder_for_plots <- paste(path_outs, current_time,'/Plots/',sep = "")
      dir.create(folder_for_plots)
    }


  } else {

    path_outs <- path.out
    if (!dir.exists(path_outs)) {
      dir.create(path_outs)
    }

    # Create a folder with the current system time as part of the folder name
    folder_out <- paste(path_outs, current_time, sep = "")
    dir.create(folder_out)

    if (get.plots == T) {
      folder_for_plots <- paste(path_outs, current_time,'/Plots/', sep = "")
      dir.create(folder_for_plots)


    }

  }


  # Create a folder with the current system time as part of the folder name
  folder_out_parameters <- paste(path_outs, current_time,'/Parameters/', sep = "")
  dir.create(folder_out_parameters)

  message <- "the SCOPE model uses the version 2.1 integrated in the SCOPEinR package "
  file_readme <-paste(folder_out_parameters,"/SCOPEversion.txt",sep='')
  writeLines(message, file_readme)
  # save using data.table
  data.table::fwrite(LUT, paste(folder_out_parameters,"/inputLUT.csv",sep=''))


  ##############################################################################################################################
  # 1.1 Get Reflectance ----
  ##############################################################################################################################

  matrix.reflapp<- matrix(nrow = 2162, ncol = nSamples+1)
  matrix.refl<- matrix(nrow = 2162, ncol = nSamples+1)
  matrix.rsd<- matrix(nrow = 2162, ncol = nSamples+1)
  matrix.rso<- matrix(nrow = 2162, ncol = nSamples+1)
  matrix.rdd<- matrix(nrow = 2162, ncol = nSamples+1)
  matrix.rdo<- matrix(nrow = 2162, ncol = nSamples+1)

  for (i in 1:length(data.sim)) {

    if (i ==1){
      wlS <- data.sim[[i]]$data.spectral$wlS
    }
    # Add reflect apparent
    reflapp <- data.sim[[i]]$data.rad$reflapp
    matrix.reflapp[, 1] <- wlS
    matrix.reflapp[, i+1] <- reflapp
    df.reflapp <- as.data.frame(matrix.reflapp)
    # Set column names as n1, n2, n3, ...
    colnames(df.reflapp) <- c("wave", paste0("n.sim", 2:ncol(df.reflapp)-1))


    # Add reflect
    refl <- data.sim[[i]]$data.rad$refl
    matrix.refl[, 1] <- wlS
    matrix.refl[, i+1] <- refl

    df.refl <- as.data.frame(matrix.refl)
    # Set column names as n1, n2, n3, ...
    colnames(df.refl) <- c("wave", paste0("n.sim", 2:ncol(df.refl)-1))

    # Add rsd
    rsd <- data.sim[[i]]$data.rad$rsd
    matrix.rsd[, 1] <- wlS
    matrix.rsd[, i+1] <- rsd

    df.rsd <- as.data.frame(matrix.rsd)
    # Set column names as n1, n2, n3, ...
    colnames(df.rsd) <- c("wave", paste0("n.sim", 2:ncol(df.rsd)-1))

    # Add rso
    rso <- data.sim[[i]]$data.rad$rso
    matrix.rso[, 1] <- wlS
    matrix.rso[, i+1] <- rso
    df.rso <- as.data.frame(matrix.rso)
    # Set column names as n1, n2, n3, ...
    colnames(df.rso) <- c("wave", paste0("n.sim", 2:ncol(df.rso)-1))

    # Add rdd
    rdd <- data.sim[[i]]$data.rad$rdd
    matrix.rdd[, 1] <- wlS
    matrix.rdd[, i+1] <- rdd
    df.rdd <- as.data.frame(matrix.rdd)
    # Set column names as n1, n2, n3, ...
    colnames(df.rdd) <- c("wave", paste0("n.sim", 2:ncol(df.rdd)-1))

    # Add rdo
    rdo <- data.sim[[i]]$data.rad$rdo
    matrix.rdo[, 1] <- wlS
    matrix.rdo[, i+1] <- rdo
    df.rdo <- as.data.frame(matrix.rdo)
    # Set column names as n1, n2, n3, ...
    colnames(df.rdo) <- c("wave", paste0("n.sim", 2:ncol(df.rdo)-1))

  }

  # save using data.table
  data.table::fwrite(df.rsd, paste(folder_out,"/rsd.csv",sep=''))
  data.table::fwrite(df.rso, paste(folder_out,"/rso.csv",sep=''))
  data.table::fwrite(df.rdd, paste(folder_out,"/rdd.csv",sep=''))
  data.table::fwrite(df.rdo, paste(folder_out,"/rdo.csv",sep=''))
  data.table::fwrite(df.refl, paste(folder_out,"/refl.csv",sep=''))
  data.table::fwrite(df.reflapp, paste(folder_out,"/reflapp.csv",sep=''))


  if (get.plots == T) {


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get rdo ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_rdo <-df.rdo %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.rdo<-ggplot(df_rdo, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2499) +
      ylab("Reflectance (rdo)") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))
    ggsave(paste(folder_for_plots,'1-reflectance_rdo.png',sep=''),plot=plot.rdo,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get rdd ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_rdd <-df.rdd %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.rdd<-ggplot(df_rdd, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2499) +
      ylab("Reflectance (rdd)") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))
    ggsave(paste(folder_for_plots,'1-reflectance_rdd.png',sep=''),plot=plot.rdd,
           width = 10, height = 10,  dpi = 300,units = "cm")


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.3 Get rso ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_rso <-df.rso %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.rso<-ggplot(df_rso, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2499) +
      ylab("Reflectance (rso)") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))
    ggsave(paste(folder_for_plots,'1-reflectance_rso.png',sep=''),plot=plot.rso,
           width = 10, height = 10,  dpi = 300,units = "cm")


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.4 Get rsd ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_rsd <-df.rsd %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.rsd<-ggplot(df_rsd, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2499) +
      ylab("Reflectance (rsd)") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))
    ggsave(paste(folder_for_plots,'1-reflectance_rsd.png',sep=''),plot=plot.rsd,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.5 Get refl  ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_refl <-df.refl %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.refl<-ggplot(df_refl, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2499) +
      ylab("Reflectance (refl)") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))
    ggsave(paste(folder_for_plots,'1-reflectance_refl.png',sep=''),plot=plot.refl,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.6 Get reflapp ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_reflapp <-df.reflapp %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.reflapp<-ggplot(df_reflapp, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2499) +
      ylab("Apparent reflectance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))
    ggsave(paste(folder_for_plots,'1-reflappectance_reflapp.png',sep=''),plot=plot.reflapp,
           width = 10, height = 10,  dpi = 300,units = "cm")




  }


  ##############################################################################################################################
  # 1.2 Get Irradiance ----
  ##############################################################################################################################

  matrix.Esun<- matrix(nrow = 2162, ncol = 1+1)
  matrix.Esky<- matrix(nrow = 2162, ncol = 1+1)


  wlS <- data.sim[[1]]$data.spectral$wlS
  i=1
  # Add Esun
  Esun <- data.sim[[1]]$data.rad$Esun_
  matrix.Esun[, 1] <- wlS
  matrix.Esun[, i+1] <- Esun
  df.Esun_ <- as.data.frame(matrix.Esun)
  # Set column names as n1, n2, n3, ...
  colnames(df.Esun_) <- c('wave','Esun')


  # Add Esky
  Esky <- data.sim[[i]]$data.rad$Esky_
  matrix.Esky[, 1] <- wlS
  matrix.Esky[, i+1] <- Esky

  df.Esky_ <- as.data.frame(matrix.Esky)
  # Set column names as n1, n2, n3, ...
  colnames(df.Esky_) <- c("wave", 'Esky')

  # save using data.table
  data.table::fwrite(df.Esun_, paste(folder_out,"/Esun.csv",sep=''))
  data.table::fwrite(df.Esky_, paste(folder_out,"/Esky.csv",sep=''))



  if (get.plots == T) {

    df.irrad <- data.frame(wave=wlS, Esun_ = df.Esun_$Esun,
                           Esky_=df.Esky_$Esky)

    p.irrad<- ggplot(data = df.irrad, aes(x = wave)) +
      geom_line(aes(y = Esun_, color = 'Esun_'), linewidth = 0.5) +
      geom_line(aes(y = Esky_, color = 'Esky_'), linewidth = 0.5) +

      scale_color_manual(name = 'Irradiance',
                         values = c('Esun_' = 'orange',
                                    'Esky_' ='grey')) +

      theme_bw() + xlim(400,2499) +
      theme(legend.position = "top") +ylab("Irradiance") +
      guides(color = guide_legend(title = NULL))

    ggsave(paste(folder_for_plots,'2-Irradiance.png',sep=''),plot=p.irrad,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }

  ##############################################################################################################################
  # 1.3 Get Radiance spectrum  excluding/adding fluorescence  (W m-2 um-1 sr-1)   ----
  ##############################################################################################################################

  matrix.Lotot_<- matrix(nrow = 2162, ncol = nSamples+1)
  matrix.Lototf_<- matrix(nrow = 2162, ncol = nSamples+1)

  for (i in 1:length(data.sim)) {

    if (i ==1){
      wlS <- data.sim[[i]]$data.spectral$wlS
    }
    # Add Lotot_
    Lotot_ <- data.sim[[i]]$data.rad$Lotot_
    matrix.Lotot_[, 1] <- wlS
    matrix.Lotot_[, i+1] <- Lotot_
    df.Lotot_<- as.data.frame(matrix.Lotot_)
    # Set column names as n1, n2, n3, ...
    colnames(df.Lotot_) <- c("wave", paste0("n.sim", 2:ncol(df.Lotot_)-1))


    # Add Lototf_
    Lototf_ <- data.sim[[i]]$data.rad$Lototf_
    matrix.Lototf_[, 1] <- wlS
    matrix.Lototf_[, i+1] <- Lototf_
    df.Lototf_<- as.data.frame(matrix.Lototf_)
    # Set column names as n1, n2, n3, ...
    colnames(df.Lototf_) <- c("wave", paste0("n.sim", 2:ncol(df.Lototf_)-1))


  }

  # save using data.table
  data.table::fwrite(df.Lotot_, paste(folder_out,"/Lo_spectrum.csv",sep=''))
  data.table::fwrite(df.Lototf_, paste(folder_out,"/Lo_spectrum_includingF.csv",sep=''))

  if (get.plots == T) {


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get Lotot_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Lotot_ <-df.Lotot_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.Lotot_<-ggplot(df_Lotot_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 900) +
      ylab("Radiance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'3-Radiance_excluding_Fluorescence.png',sep=''),plot=plot.Lotot_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get Lototf_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Lototf_ <-df.Lototf_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.Lototf_<-ggplot(df_Lototf_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 900) +
      ylab("Radiance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'3-Radiance_adding_Fluorescence.png',sep=''),plot=plot.Lototf_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }



  ##############################################################################################################################
  # 1.4 Get Radiation  ----
  ##############################################################################################################################



  matrix.radiation<- matrix(nrow = nSamples, ncol = 5)


  for (i in 1:length(data.sim)) {

    # Add radiation data
    n.sim <-i
    Rin <- data.sim[[i]]$data.meteo$Rin
    Rli <- data.sim[[i]]$data.meteo$Rli
    Eouto <- data.sim[[i]]$data.rad$Eouto
    Eoutte <- data.sim[[i]]$data.rad$Eoutte

    matrix.radiation[i,] <- c(n.sim,Rin,Rli,Eouto,Eoutte)

    df.radiation<- as.data.frame(matrix.radiation)
    # Set column names as n1, n2, n3, ...
    colnames(df.radiation) <- c('n.sim','ShortIn','ShortLong','HemisOutIn','HemisOutLong')
  }

  # save using data.table
  data.table::fwrite(df.radiation, paste(folder_out,"/radiation.csv",sep=''))


  df.radiation.units <- data.frame(ShortIn = 'W m-2', ShortLong = 'W m-2',
                                   HemisOutIn = 'W m-2', HemisOutLong = 'W m-2',
                                   Lo = 'W m-2 sr -1', Lot = 'W m-2 sr -1', Lote = 'W m-2 sr -1')


  # save using data.table
  data.table::fwrite(df.radiation.units, paste(folder_out,"/radiation_units.csv",sep=''))


  ##############################################################################################################################
  # 1.5 Get ApAR values  ----
  ##############################################################################################################################



  matrix.apar<- matrix(nrow = 21, ncol = nSamples)

  for (i in 1:length(data.sim)) {

    # Add number of sim
    n.sim <-i

    # EPAR and PAR
    iPAR =  data.sim[[i]]$data.rad[['PAR']] ## units in umol m-2 s-1
    iPARE =  data.sim[[i]]$data.rad[['EPAR']] ## units in W m-2
    ## LAI sunit/sgaded
    LAIsunlit =  data.sim[[i]]$data.canopy[['LAIsunlit']] ## m2 m-2
    LAIshaded =  data.sim[[i]]$data.canopy[['LAIshaded']] ## m2 m-2
    # Total aPAR
    aPARTot =  data.sim[[i]]$data.canopy[['Pntot']] ## units in umol m-2 s-1
    aPARTotSun =  data.sim[[i]]$data.canopy[['Pnsun']] ## units in umol m-2 s-1
    aPARTotShaded =  data.sim[[i]]$data.canopy[['Pnsha']] ## units in umol m-2 s-1

    ## Total aPAR Cab
    aPARCabTot =  data.sim[[i]]$data.canopy[['Pntot_Cab']] ## units in umol m-2 s-1
    aPARCabSun =  data.sim[[i]]$data.canopy[['Pnsun_Cab']] ## units in umol m-2 s-1
    aPARCabShaded =  data.sim[[i]]$data.canopy[['Pnsha_Cab']] ## units in umol m-2 s-1

    ## Total aPAR Car
    aPARCarTot =  data.sim[[i]]$data.canopy[['Pntot_Car']] ## units in umol m-2 s-1
    aPARCarSun =  data.sim[[i]]$data.canopy[['Pnsun_Car']] ## units in umol m-2 s-1
    aPARCarShaded =  data.sim[[i]]$data.canopy[['Pnsha_Car']] ## units in umol m-2 s-1

    # Total aPAR E
    aPARTotE =  data.sim[[i]]$ata.canopy[['Rntot_PAR']] ## units in W m-2
    aPARTotSunE =  data.sim[[i]]$data.canopy[['Rnsun_PAR']] ##  units in W m-2
    aPARTotShadedE =  data.sim[[i]]$data.canopy[['Rnsha_PAR']] ## units in m-2

    # Total aPAR E Cab
    aPARTotCabE =  data.sim[[i]]$data.canopy[['Rntot_Cab']] ## units in W m-2
    aPARTotSunCabE =  data.sim[[i]]$data.canopy[['Rnsun_Car']]##  units in W m-2
    aPARTotShadedCabE =  data.sim[[i]]$data.canopy[['Rnsha_Car']] ## units in W m-2

    # Total aPAR E Car
    aPARTotCarE =  data.sim[[i]]$data.canopy[['Rntot_Car']] ## units in W m-2
    aPARTotSunCarE =  data.sim[[i]]$data.canopy[['Rnsun_Car']] ##  units in W m-2
    aPARTotShadedCarE =  data.sim[[i]]$data.canopy[['Rnsha_Car']]## units in W m-2

    data.apar <-rbind(iPAR, iPARE,
          LAIsunlit, LAIshaded,
          aPARTot, aPARTotSun, aPARTotShaded,
          aPARCabTot, aPARCabSun, aPARCabShaded,
          aPARCarTot, aPARCarSun, aPARCarShaded,
          aPARTotE, aPARTotSunE, aPARTotShadedE,
          aPARTotCabE, aPARTotSunCabE, aPARTotShadedCabE,
          aPARTotCarE, aPARTotSunCarE,aPARTotShadedCarE)
    matrix.apar[,i] <- data.apar

  }

  df.apar<- as.data.frame(matrix.apar)
  var.names <-rownames(data.apar)
  df.apar<-cbind(var.names,df.apar)
  # Set column names as n1, n2, n3, ...
  colnames(df.apar) <- c("Variable", paste0("n.sim", 2:ncol(df.apar)-1))

  # save using data.table
  data.table::fwrite(df.apar, paste(folder_out,"/aPAR.csv",sep=''))

  ##############################################################################################################################
  # 1.6 Get resistance values  ----
  ##############################################################################################################################

  matrix.resistance<- matrix(nrow = 4, ncol = nSamples)

  for (i in 1:length(data.sim)) {

    ra = data.sim[[i]]$resist_out[['raws']] ## units in s m-1
    raforSoil = data.sim[[i]]$resist_out[['rss']] ## units in s m-1
    rss = data.sim[[i]]$resist_out[['rss']] ## units in s m-1
    ustar = data.sim[[i]]$resist_out[['ustar']] ## units in m2 s-1

    data.resistance <-rbind(ra, raforSoil,rss,ustar)
    matrix.resistance[,i] <- data.resistance

  }
  df.resistance <- as.data.frame(matrix.resistance)
  var.names <-rownames(df.resistance)
  df.resistance<-cbind(var.names,df.resistance)
  # Set column names as n1, n2, n3, ...
  colnames(df.resistance) <- c("Variable", paste0("n.sim", 2:ncol(df.resistance)-1))

  # save using data.table
  data.table::fwrite(df.resistance, paste(folder_out,"/resistance.csv",sep=''))

  df.resistance.units <-data.frame(ra = 's m-1', raforSoil = 's m-1',
                                   rss = 's m-1', ustar ='m2 s-1')

  # save using data.table
  data.table::fwrite(df.resistance.units, paste(folder_out,"/resistance_units.csv",sep=''))

  ##############################################################################################################################
  # 1.7 Get vegetation values  ----
  ##############################################################################################################################


  matrix.vegetation<- matrix(nrow = 6, ncol = nSamples)

  for (i in 1:length(data.sim)) {

    Photosintesis = data.sim[[i]]$data.canopy[['A']] ## units in umol m-2 s-1
    Electron_transport = data.sim[[i]]$data.canopy[['Ja']] ## units in umol m-2 s-1
    NPQ_energy = data.sim[[i]]$data.canopy[['ENPQ']] ## units in W m-2
    NPQ_photon = data.sim[[i]]$data.canopy[['PNPQ']] ## units in umol photons-1
    LST = data.sim[[i]]$data.canopy[['LST']] ## units in K
    emis = data.sim[[i]]$data.canopy[['emis']] ##  no units

    data.vegetation <-rbind(Photosintesis, Electron_transport,NPQ_energy,NPQ_photon,LST,emis)
    matrix.vegetation[,i] <- data.vegetation

  }
  df.vegetation <- as.data.frame(matrix.vegetation)
  var.names <-rownames(df.vegetation)
  df.vegetation<-cbind(var.names,df.vegetation)
  # Set column names as n1, n2, n3, ...
  colnames(df.vegetation) <- c("Variable", paste0("n.sim", 2:ncol(df.vegetation)-1))


  data.table::fwrite(df.vegetation, paste(folder_out,"/vegatation.csv",sep=''))

  df.vegatation.units <-data.frame(Photosintesis = 'umol m-2 s-1', Electron_transport = 'umol m-2 s-1',
                                   NPQ_energy = 'W m-2',  NPQ_photon = 'umol photons-1',
                                  LST = 'Kelvin', emis = '--')
  # save using data.table
  data.table::fwrite(df.vegatation.units, paste(folder_out,"/vegatation_units.csv",sep=''))

  ##############################################################################################################################
  # 1.8 Get Sigma Fluorescence values  ----
  ##############################################################################################################################


  matrix.sigmaF<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)

  for (i in 1:length(data.sim)) {

    if (i ==1){
      wlF <- data.sim[[i]]$data.spectral$wlF
    }
    # Add sigmaF
    sigmaF = data.sim[[i]]$data.rad$sigmaF
    matrix.sigmaF[, 1] <- wlF
    matrix.sigmaF[, i+1] <- sigmaF
    df.sigmaF<- as.data.frame(matrix.sigmaF)
    # Set column names as n1, n2, n3, ...
    colnames(df.sigmaF) <- c("wave", paste0("n.sim", 2:ncol(df.sigmaF)-1))


  }

  # save using data.table
  data.table::fwrite(df.sigmaF, paste(folder_out,"/SigmaF.csv",sep=''))

  if (get.plots == T) {


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get sigmaF ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_sigmaF_ <-df.sigmaF %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.sigmaF_ <-ggplot(df_sigmaF_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("sigmaF") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'4-SigmaFluorescence.png',sep=''),plot=plot.sigmaF_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }

  ##############################################################################################################################
  # 1.8 Get Hemispherically Integrated upwelling radiance or TOC upward radiation  (W m-2 um-1)   ----
  ##############################################################################################################################



  matrix.Eout_<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlS), ncol = nSamples+1)

  for (i in 1:length(data.sim)) {

    if (i ==1){
      wlS <- data.sim[[i]]$data.spectral$wlS
    }
    # Add Eout_
    Eout_ = data.sim[[i]]$data.rad$Eout_
    matrix.Eout_[, 1] <- wlS
    matrix.Eout_[, i+1] <- Eout_
    df.Eout_<- as.data.frame(matrix.Eout_)
    # Set column names as n1, n2, n3, ...
    colnames(df.Eout_) <- c("wave", paste0("n.sim", 2:ncol(df.Eout_)-1))


  }

  # save using data.table
  data.table::fwrite(df.Eout_, paste(folder_out,"/Eout_spectrum.csv",sep=''))

  if (get.plots == T) {


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get Eout_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Eout_ <-df.Eout_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.Eout_ <-ggplot(df_Eout_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(400, 2500) +
      ylab("Radiance") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'5-Hemispherically_Integrated_upwelling_radiance.png',sep=''),plot=plot.Eout_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }


  ##############################################################################################################################
  # 1.9 Get Fluxes  ----
  ##############################################################################################################################


  df.fluxes <- as.data.frame(t(unlist(data.sim[[1]]$data.fluxes)))
  matrix.fluxes<- matrix(nrow = nSamples, ncol = dim(df.fluxes)[2])


  for (i in 1:length(data.sim)) {

    fluxes<- unlist(data.sim[[i]]$data.fluxes)
    matrix.fluxes[i,] <- fluxes

  }
  df.fluxes <- as.data.frame(matrix.fluxes)
  var.names <-names(fluxes)
  n.sim<-c(1:nSamples)
  df.fluxes<-cbind(n.sim,df.fluxes)
  # Set column names as n1, n2, n3, ...
  colnames(df.fluxes) <- c("n.sim", var.names)

  # save using data.table
  data.table::fwrite(df.fluxes, paste(folder_out,"/fluxes.csv",sep=''))


  df.fluxes.units<-data.frame( Rnctot = 'W m-2', lEctot = 'W m-2', Hctot = 'W m-2', Actot = 'umol m-2 s-1',
    Tcave = 'C', Rnstot = 'W m-2',  lEstot = 'W m-2', Hstot= 'W m-2',
    Gtot= 'W m-2', Tsave = 'C',Rntot = 'W m-2', lEtot ='W m-2',
    Htot ='W m-2')
  # save using data.table
  data.table::fwrite(df.fluxes.units, paste(folder_out,"/fluxes_units.csv",sep=''))


  ##############################################################################################################################
  # 1.10 Get fluorescence  (W m-2 um-1 sr-1)   ----
  ##############################################################################################################################

  matrix.LoF_<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  matrix.LoF_sunlit<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  matrix.LoF_shaded<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  matrix.LoF_scattered<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  matrix.LoF_soil<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  ## All leaves
  matrix.Femliave_<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  matrix.EoutF_<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)
  matrix.EoutFrc_<- matrix(nrow = length(data.sim[[1]]$data.spectral$wlF), ncol = nSamples+1)

  for (i in 1:length(data.sim)) {

    if (i ==1){
      wlF <- data.sim[[i]]$data.spectral$wlF
    }

    # Add LoF_
    LoF_ = data.sim[[i]]$data.rad$LoF_
    matrix.LoF_[, 1] <- wlF
    matrix.LoF_[, i+1] <- LoF_
    df.LoF_<- as.data.frame(matrix.LoF_)

    ##

    # Set column names as n1, n2, n3, ...
    colnames(df.LoF_) <- c("wave", paste0("n.sim", 2:ncol(df.LoF_)-1))


    # Add LoF_sunlit
    LoF_sunlit = data.sim[[i]]$data.rad$LoF_sunlit
    matrix.LoF_sunlit[, 1] <- wlF
    matrix.LoF_sunlit[, i+1] <- LoF_sunlit
    df.LoF_sunlit<- as.data.frame(matrix.LoF_sunlit)
    # Set column names as n1, n2, n3, ...
    colnames(df.LoF_sunlit) <- c("wave", paste0("n.sim", 2:ncol(df.LoF_sunlit)-1))

    # Add LoF_shaded
    LoF_shaded = data.sim[[i]]$data.rad$LoF_shaded
    matrix.LoF_shaded[, 1] <- wlF
    matrix.LoF_shaded[, i+1] <- LoF_shaded
    df.LoF_shaded<- as.data.frame(matrix.LoF_shaded)
    # Set column names as n1, n2, n3, ...
    colnames(df.LoF_shaded) <- c("wave", paste0("n.sim", 2:ncol(df.LoF_shaded)-1))


    # Add LoF_scattered
    LoF_scattered = data.sim[[i]]$data.rad$LoF_scattered
    matrix.LoF_scattered[, 1] <- wlF
    matrix.LoF_scattered[, i+1] <- LoF_scattered
    df.LoF_scattered<- as.data.frame(matrix.LoF_scattered)
    # Set column names as n1, n2, n3, ...
    colnames(df.LoF_scattered) <- c("wave", paste0("n.sim", 2:ncol(df.LoF_scattered)-1))



    # Add LoF_soil
    LoF_scattered = data.sim[[i]]$data.rad$LoF_scattered
    matrix.LoF_soil[, 1] <- wlF
    matrix.LoF_soil[, i+1] <- LoF_scattered
    df.LoF_soil<- as.data.frame(matrix.LoF_soil)
    # Set column names as n1, n2, n3, ...
    colnames(df.LoF_soil) <- c("wave", paste0("n.sim", 2:ncol(df.LoF_soil)-1))


    # Add Femliave_ (Fluorescence for all leaves)
    Femliave_ = data.sim[[i]]$data.rad$Femliave_
    matrix.Femliave_[, 1] <- wlF
    matrix.Femliave_[, i+1] <- Femliave_
    df.Femliave_<- as.data.frame(matrix.Femliave_)
    # Set column names as n1, n2, n3, ...
    colnames(df.Femliave_) <- c("wave", paste0("n.sim", 2:ncol(df.Femliave_)-1))

    # Add EoutF_
    EoutF_ = data.sim[[i]]$data.rad$EoutF_
    matrix.EoutF_[, 1] <- wlF
    matrix.EoutF_[, i+1] <- EoutF_
    df.EoutF_<- as.data.frame(matrix.EoutF_)
    # Set column names as n1, n2, n3, ...
    colnames(df.EoutF_) <- c("wave", paste0("n.sim", 2:ncol(df.EoutF_)-1))

    # Add EoutFrc_
    EoutFrc_ = data.sim[[i]]$data.rad$EoutFrc_
    matrix.EoutFrc_[, 1] <- wlF
    matrix.EoutFrc_[, i+1] <- EoutFrc_
    df.EoutFrc_<- as.data.frame(matrix.EoutFrc_)
    # Set column names as n1, n2, n3, ...
    colnames(df.EoutFrc_) <- c("wave", paste0("n.sim", 2:ncol(df.EoutFrc_)-1))


  }

  # save using data.table
  data.table::fwrite(df.LoF_, paste(folder_out,"/fluorescence.csv",sep=''))
  data.table::fwrite(df.LoF_sunlit, paste(folder_out,"/fluorescence_sunlit.csv",sep=''))
  data.table::fwrite(df.LoF_shaded, paste(folder_out,"/fluorescence_shaded.csv",sep=''))
  data.table::fwrite(df.LoF_soil, paste(folder_out,"/fluorescence_soil.csv",sep=''))
  data.table::fwrite(df.LoF_scattered, paste(folder_out,"/fluorescence_scattered.csv",sep=''))

  data.table::fwrite(df.Femliave_, paste(folder_out,"/fluorescence_All_Leaves.csv",sep=''))
  data.table::fwrite(df.EoutF_, paste(folder_out,"/fluorescence_hemis.csv",sep=''))
  data.table::fwrite(df.EoutFrc_, paste(folder_out,"/fluorescence_ReabsCorr.csv",sep=''))


  if (get.plots == T) {


    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.1 Get df.LoF_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Define custom colors for the legend
    colors <- c("red", "blue", "green")  # You can modify the colors as needed


    # Reshape the data frame into a long format
    df_LoF_ <-df.LoF_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))

    #print(plot.LoF_)
    ggsave(paste(folder_for_plots,'6-fluorescence.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")



    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get df.LoF_sunlit ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_sunlit <-df.LoF_sunlit %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_sunlit, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence sunlit") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_sunlit.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get df.LoF_shaded ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_shaded <-df.LoF_shaded %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_shaded, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence shaded") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_shaded.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")



    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.3 Get df.LoF_scattered ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_scattered <-df.LoF_scattered %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_scattered, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence scattered") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_scattered.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")
    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.4 Get df.LoF_soil ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_LoF_soil <-df.LoF_soil %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.LoF_ <-ggplot(df_LoF_soil, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence soil") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_soil.png',sep=''),plot=plot.LoF_,
           width = 10, height = 10,  dpi = 300,units = "cm")



    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.5 Get df.Femliave_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_Femliave_<-df.Femliave_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.Femliave_ <-ggplot(df_Femliave_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_AllLeaves.png',sep=''),plot=plot.Femliave_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.2 Get df.EoutF_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_EoutF_<-df.EoutF_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.EoutF_ <-ggplot(df_EoutF_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_hemis.png',sep=''),plot=plot.EoutF_,
           width = 10, height = 10,  dpi = 300,units = "cm")

    # :::::::::::::::::::::::::::::::::::::::::::::
    # 1.6 Get df.EoutFrc_ ----
    # :::::::::::::::::::::::::::::::::::::::::::::

    # Reshape the data frame into a long format
    df_EoutFrc_<-df.EoutFrc_ %>%
      gather(n.sim, value, -wave)

    # Plot all spectra in a single plot
    plot.EoutFrc_ <-ggplot(df_EoutFrc_, aes(x = wave, y = value, color =  n.sim, group =  n.sim)) +
      geom_line(linewidth = 0.5) +
      theme_bw() +
      xlim(640, 850) +
      ylab("Fluorescence") +
      theme(legend.position = "none") +
      guides(color = guide_legend(title = NULL))


    ggsave(paste(folder_for_plots,'6-fluorescence_ReabsCorr.png',sep=''),plot=plot.EoutFrc_,
           width = 10, height = 10,  dpi = 300,units = "cm")


  }


  ##############################################################################################################################
  # 1.10 Get fluorescence scalar values     ----
  ##############################################################################################################################


  matrix.scalar<- matrix(nrow = 9, ncol = nSamples)

  for (i in 1:length(data.sim)) {

    F_1stPeak = data.sim[[i]]$data.rad[['F685']]
    wl_1stPeak = data.sim[[i]]$data.rad[['wl685']]
    F_2ndPeak = data.sim[[i]]$data.rad[['F740']]
    wl_2ndPeak = data.sim[[i]]$data.rad[['wl740']]
    F684 = data.sim[[i]]$data.rad[['F684']]
    F761 = data.sim[[i]]$data.rad[['F761']]
    LFtot = data.sim[[i]]$data.rad[['LoutF']]
    EFtot = data.sim[[i]]$data.rad[['EoutF']]
    EFtot_RC = data.sim[[i]]$data.rad[['EoutFrc']]


    data.scalar <-rbind(F_1stPeak, wl_1stPeak,F_2ndPeak,wl_2ndPeak,
                        F684,F761,LFtot,EFtot,EFtot_RC)
    matrix.scalar[,i] <- data.scalar

  }
  df.scalar <- as.data.frame(matrix.scalar)
  var.names <-rownames(df.scalar)
  df.scalar<-cbind(var.names,df.scalar)
  # Set column names as n1, n2, n3, ...
  colnames(df.scalar) <- c("Variable", paste0("n.sim", 2:ncol(df.scalar)-1))

  # save using data.table
  data.table::fwrite(df.scalar, paste(folder_out,"/fluorescence_scalar.csv",sep=''))

  df.scalar.units<-data.frame( F_1stPeak = 'W m-2 um-1 sr-1', wl_1stPeak = 'nm',
                               F_2ndPeak = 'W m-2 um-1 sr-1', wl_2ndPeak = 'nm',
                               F684 = 'W m-2 um-1 sr-1', F761 = 'W m-2 um-1 sr-1',
                               LFtot= 'W m-2 sr-1',EFtot = 'W m-2', EFtot_RC ='W m-2')
  # save using data.table
  data.table::fwrite(df.scalar, paste(folder_out,"/fluorescence_scalar_units.csv",sep=''))





}


